application: goblog
version: 1
runtime: go
api_version: go1

handlers:
- url: /css
  static_dir: static/stylesheets

- url: /img
  static_dir: static/img

- url: /js
  static_dir: static/js

- url: /admin/.*
  script: _go_app
  login: admin

- url: /.*
  script: _go_app
